# Generated by Django 3.2.8 on 2021-10-31 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodis_blog', '0002_auto_20211029_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_created',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_modified',
            new_name='updated_on',
        ),
        migrations.RemoveField(
            model_name='post',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published',
        ),
        migrations.RemoveField(
            model_name='post',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
    ]
